### ISSUE TITLE
Magento coding standards php not working with linux getting error like image's platform (linux/arm64) does not match the detected

### ISSUE THREAD

**Issue by sarfaraz27** [pwalus/codexpect-magento#5]
HI @pwalus 

I have setup in my local machine magento with warden, Now I m going to add your changes which you mention in warden-env.yml ` codexpect/magento-coding-standards-php:8.1.14-cli`  .

I m getting below error, that image what you push on docker that is not compatible with linux. 
![Screenshot from 2024-02-09 10-34-56](https://github.com/pwalus/codexpect-magento/assets/8222555/034cd8f7-5f64-45c7-9f45-e5ae6a5e7c1e)

**Error**:- coding-standards The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested 

Thank you 
Shaikh Sarfaraz Ahmed

**Comment by pwalus** [comment]
Hello @sarfaraz27,
Thanks for reporting that. I've just rebuilt docker images for linux/amd64 and linux/arm64 so it should work now. 

Let me know if that helps :)

**Comment by sarfaraz27** [comment]
Thank you @pwalus  now it's working for linux/arm64.
